# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e861c563d4572660872d43412e07f00bdb8b2ba32208f64ffa317d4441adeefe2515996fab6a095c4bf55e9152758a9f1ec11a7ec26a69dc95528bdd4c4b1a76

test:
  secret_key_base: df3f6fed08eae1ede37749fe654fe1cb5675b3c41e08e18c1f38c45a85a7100275ebcd39775f3d6a64759c11836c7b1d508432a09100d84871f3025a515758f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
